package com.benz.here.search.service;

import org.json.JSONArray;
import org.json.JSONObject;

public class Test {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//String str = "{\\r\\n    \\\"Response\\\": {\\r\\n        \\\"MetaInfo\\\": {\\r\\n            \\\"Timestamp\\\": \\\"2020-09-13T07:03:42.233+0000\\\"\\r\\n        },\\r\\n        \\\"View\\\": [\\r\\n            {\\r\\n                \\\"_type\\\": \\\"SearchResultsViewType\\\",\\r\\n                \\\"ViewId\\\": 0,\\r\\n                \\\"Result\\\": [\\r\\n                    {\\r\\n                        \\\"Relevance\\\": 1.0,\\r\\n                        \\\"MatchLevel\\\": \\\"country\\\",\\r\\n                        \\\"MatchQuality\\\": {\\r\\n                            \\\"Country\\\": 1.0\\r\\n                        },\\r\\n                        \\\"Location\\\": {\\r\\n                            \\\"LocationId\\\": \\\"NT_b9zulvNJImyXifwjSe54wC\\\",\\r\\n                            \\\"LocationType\\\": \\\"point\\\",\\r\\n                            \\\"DisplayPosition\\\": {\\r\\n                                \\\"Latitude\\\": 40.41956,\\r\\n                                \\\"Longitude\\\": -3.69196\\r\\n                            },\\r\\n                            \\\"NavigationPosition\\\": [\\r\\n                                {\\r\\n                                    \\\"Latitude\\\": 40.41956,\\r\\n                                    \\\"Longitude\\\": -3.69196\\r\\n                                }\\r\\n                            ],\\r\\n                            \\\"MapView\\\": {\\r\\n                                \\\"TopLeft\\\": {\\r\\n                                    \\\"Latitude\\\": 43.78989,\\r\\n                                    \\\"Longitude\\\": -9.30152\\r\\n                                },\\r\\n                                \\\"BottomRight\\\": {\\r\\n                                    \\\"Latitude\\\": 35.21301,\\r\\n                                    \\\"Longitude\\\": 4.32788\\r\\n                                }\\r\\n                            },\\r\\n                            \\\"Address\\\": {\\r\\n                                \\\"Label\\\": \\\"Espa\\u00F1a\\\",\\r\\n                                \\\"Country\\\": \\\"ESP\\\",\\r\\n                                \\\"AdditionalData\\\": [\\r\\n                                    {\\r\\n                                        \\\"value\\\": \\\"Espa\\u00F1a\\\",\\r\\n                                        \\\"key\\\": \\\"CountryName\\\"\\r\\n                                    }\\r\\n                                ]\\r\\n                            }\\r\\n                        }\\r\\n                    }\\r\\n                ]\\r\\n            }\\r\\n        ]\\r\\n    }\\r\\n}";
		String s = "{\"Response\":{\"MetaInfo\":{\"Timestamp\":\"2020-09-13T06:57:59.350+0000\"},\"View\":[{\"_type\":\"SearchResultsViewType\",\"ViewId\":0,\"Result\":[{\"Relevance\":1.0,\"MatchLevel\":\"city\",\"MatchQuality\":{\"City\":1.0},\"Location\":{\"LocationId\":\"NT_DKX2wfaWICS7JyfHmCOJhB\",\"LocationType\":\"point\",\"DisplayPosition\":{\"Latitude\":52.51605,\"Longitude\":13.37691},\"NavigationPosition\":[{\"Latitude\":52.51605,\"Longitude\":13.37691}],\"MapView\":{\"TopLeft\":{\"Latitude\":52.66058,\"Longitude\":13.11938},\"BottomRight\":{\"Latitude\":52.37615,\"Longitude\":13.65801}},\"Address\":{\"Label\":\"Berlin, Deutschland\",\"Country\":\"DEU\",\"State\":\"Berlin\",\"County\":\"Berlin\",\"City\":\"Berlin\",\"PostalCode\":\"10117\",\"AdditionalData\":[{\"value\":\"Deutschland\",\"key\":\"CountryName\"},{\"value\":\"Berlin\",\"key\":\"StateName\"},{\"value\":\"Berlin\",\"key\":\"CountyName\"}]}}}]}]}}";
		
		
		

	}

}
